import Link from "next/link";
import styles from "./iterations.module.css";

const requirements = [
  { id: "ally-intent", story: "As David, I tell my Ally to bring Jeya and Aashik together without learning a creation workflow.", addressed: "Ally intent field interprets natural language and creates a secret Community Envoy.", link: "/?place=field", label: "Try in the Field" },
  { id: "three-views", story: "As a prototype tester, I can experience the same community as David, Jeya, or Aashik in separate browsers.", addressed: "Prototype sign-in persists one identity per browser; Faces and Ally identities change contextually.", link: "/?place=field", label: "Choose an identity" },
  { id: "community", story: "As a member, I inspect a community as a living connection—not merely a list of people.", addressed: "Community Pulse, Envoy capabilities, privacy, Faces, and invitation state live in one inspectable place.", link: "/?place=community", label: "Inspect community" },
  { id: "faces", story: "As a member, I recognize people immediately and contact them without demanding their attention.", addressed: "Distinctive generated Faces open contextual cards with Ally-mediated message, urgent, and share actions.", link: "/?place=community", label: "Open a Face" },
  { id: "project", story: "As a community, we can have focused projects with their own Envoys, actors, and scoped knowledge.", addressed: "The project exists inside the community and exposes work, Wisdom, Actors, and Signals without becoming a chat room.", link: "/?place=project", label: "Enter the project" },
  { id: "wisdom", story: "As a contributor, I open useful research to the project without forcing everyone to read raw documents.", addressed: "Sources enter a private Wisdom namespace and appear through synthesis, concepts, provenance, and scope.", link: "/?place=wisdom", label: "Explore Wisdom" },
  { id: "mapper", story: "As a member, I understand what Mapper does and what it is allowed to do.", addressed: "Mapper is a visible project Actor: read-only, scoped to project Wisdom, producing synthesized Signals—not messages.", link: "/?place=project", label: "Inspect Mapper" },
  { id: "attention", story: "As a member, I see only meaningful movements that require me.", addressed: "Signals replace group conversation and status feeds; a single direction opens in a nearly opaque focus surface.", link: "/?place=signals", label: "Review a Signal" },
  { id: "living", story: "As a decision maker, I respond in a small human chunk and retain provenance without reading a formal brief.", addressed: "A concise contextual direction can be accepted into living Wisdom with an invisible event receipt.", link: "/?place=signals", label: "Make a direction live" },
];

export default function IterationsPage() {
  return <main className={styles.page}>
    <header className={styles.top}><Link href="/">← Return to Studio</Link><span>STUDIO UX SPECIFICATION</span><b>living document · 15 July 2026</b></header>
    <section className={styles.hero}><span>THE PROTOTYPE LEDGER</span><h1>From intention<br/>to observable behavior.</h1><p>This is not the production backlog. It is the evolving UX specification: prompts, decisions, use cases, and direct links into the interface that demonstrates each idea.</p></section>

    <nav className={styles.versions}><a href="#v02"><b>0.2</b><span>Living Field</span><em>current</em></a><a href="#v01"><b>0.1</b><span>Spatial workflow</span><em>archived</em></a></nav>

    <section id="v02" className={styles.iteration}>
      <header><div><span>ITERATION 0.2 · CURRENT</span><h2>The Living Field</h2><p>Natural navigation, Ally-directed intent, playable identities, Faces, Envoys, Wisdom, Actors, and Signals.</p></div><Link href="/">Open prototype →</Link></header>
      <details><summary>Prompt that shaped this iteration <span>View edited prompt</span></summary><div className={styles.prompt}><p><strong>Core direction</strong></p><p>Make this look like the real system: a true high-fidelity UX prototype with natural navigation, a React front end, persistent database logic, and realistic OpenAI-backed Ally interaction.</p><p>Make the interface magical and alive—subtle sparkles and flares, geometric and organic forms, gradients and texture. Move beyond dreary olive and caramel. This is an interface for the living agentic field, not a browser of dead media.</p><p>Reframe the journey around asking David’s Ally to bring Jeya and Aashik together. If no formal Alliance is named, create a Community Envoy. Every non-member entity has an Envoy; every member has an Ally. Communities carry Wisdom, Stance, Connections, Skills, Automations, and privacy.</p><p>Replace initials and traditional profile photos with distinct iconic Faces. Face inspection should reveal contextual contribution and Ally-mediated actions that protect attention.</p><p>Projects exist within communities and have their own Envoys, Wisdom, Actors, and privacy. Source artifacts should become processed Wisdom, not a wall of document cards. Mapper must have a legible purpose and scope.</p><p>Do not reproduce group chat. Allies and external connection agents synthesize work into organized knowledge and intelligent Signals. Avoid formal briefs: surface small responsive chunks and approvals only when judgment is truly needed.</p><p>Add simple three-account prototype sign-in, preserve prompts and prototype versions, and link every specification to the experience that demonstrates it.</p><p><em>Security edit: the OpenAI API credential pasted into the original prompt is intentionally omitted and must be rotated.</em></p></div></details>
      <div className={styles.specHeader}><span>USE CASE / STORY</span><span>OBSERVABLE SPECIFICATION</span><span>PROTOTYPE</span></div>
      <div className={styles.requirements}>{requirements.map((item, index) => <article key={item.id} id={item.id}><b>{String(index + 1).padStart(2,"0")}</b><p>{item.story}</p><p>{item.addressed}</p><Link href={item.link}>{item.label} →</Link></article>)}</div>
    </section>

    <section id="v01" className={`${styles.iteration} ${styles.archived}`}>
      <header><div><span>ITERATION 0.1 · ARCHIVED</span><h2>Spatial workflow</h2><p>Eight staged screens exploring Field continuity, community boundaries, project work, chat focus, and approval receipts.</p></div><a href="https://kiduna-studio-prototype-e3f9opqw1-motocoasters-projects.vercel.app">Open archived deployment →</a></header>
      <details><summary>Prompt that shaped this iteration <span>View summary</span></summary><div className={styles.prompt}><p>Starting from the Spatial UI Domain Model, Surfaces Design Bible, and July 15 meeting notes, create high-fidelity Studio screens in which one member invites two others into a community and then starts and works through a project. The Field should always remain present. When chat or specific information takes focus, the HUD should become almost opaque. Explore how organizations, communities, projects, artifacts, agents, and members are represented.</p></div></details>
      <div className={styles.lessons}><span>WHAT 0.1 TAUGHT US</span><p>The Field continuity and focus-depth ideas were worth keeping. The linear steps, “gather” metaphor, oversized artifact cards, group conversation, and formal approval brief were not. Iteration 0.2 turns those findings into a navigable behavioral specification.</p></div>
    </section>
  </main>;
}
