/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  varchar,
  timestamp,
  integer,
  boolean,
  numeric,
  jsonb,
  text,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_tenants_template = pgEnum('enum_tenants_template', [
  'website',
  'portfolio',
  'blog',
  'landing',
])
export const enum_tenants_status = pgEnum('enum_tenants_status', [
  'provisioning',
  'active',
  'suspended',
])
export const enum_cms_users_roles = pgEnum('enum_cms_users_roles', [
  'super-admin',
  'site-manager',
])
export const enum_posts_status = pgEnum('enum_posts_status', [
  'draft',
  'published',
])
export const enum__posts_v_version_status = pgEnum(
  'enum__posts_v_version_status',
  ['draft', 'published']
)
export const enum_pages_blocks_call_to_action_links_link_type = pgEnum(
  'enum_pages_blocks_call_to_action_links_link_type',
  ['primary', 'secondary']
)
export const enum_pages_hero_type = pgEnum('enum_pages_hero_type', [
  'none',
  'lowImpact',
  'mediumImpact',
  'highImpact',
])
export const enum_pages_status = pgEnum('enum_pages_status', [
  'draft',
  'published',
])
export const enum__pages_v_blocks_call_to_action_links_link_type = pgEnum(
  'enum__pages_v_blocks_call_to_action_links_link_type',
  ['primary', 'secondary']
)
export const enum__pages_v_version_hero_type = pgEnum(
  'enum__pages_v_version_hero_type',
  ['none', 'lowImpact', 'mediumImpact', 'highImpact']
)
export const enum__pages_v_version_status = pgEnum(
  'enum__pages_v_version_status',
  ['draft', 'published']
)
export const enum_footer_socials_platform = pgEnum(
  'enum_footer_socials_platform',
  ['twitter', 'github', 'linkedin', 'instagram', 'youtube']
)
export const enum_settings_typography_base_font_size = pgEnum(
  'enum_settings_typography_base_font_size',
  ['14', '16', '18']
)

export const tenants = pgTable(
  'tenants',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    ownerWallet: varchar('owner_wallet').notNull(),
    template: enum_tenants_template('template').notNull().default('website'),
    status: enum_tenants_status('status').notNull().default('provisioning'),
    mcpApiKey: varchar('mcp_api_key'),
    globalToolAccountId: varchar('global_tool_account_id'),
    siteUrl: varchar('site_url'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('tenants_slug_idx').on(columns.slug),
    index('tenants_updated_at_idx').on(columns.updatedAt),
    index('tenants_created_at_idx').on(columns.createdAt),
  ]
)

export const cms_users_roles = pgTable(
  'cms_users_roles',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_cms_users_roles('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('cms_users_roles_order_idx').on(columns.order),
    index('cms_users_roles_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [cms_users.id],
      name: 'cms_users_roles_parent_fk',
    }).onDelete('cascade'),
  ]
)

export const cms_users_tenants = pgTable(
  'cms_users_tenants',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    tenant: integer('tenant_id')
      .notNull()
      .references(() => tenants.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => [
    index('cms_users_tenants_order_idx').on(columns._order),
    index('cms_users_tenants_parent_id_idx').on(columns._parentID),
    index('cms_users_tenants_tenant_idx').on(columns.tenant),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cms_users.id],
      name: 'cms_users_tenants_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const cms_users_sessions = pgTable(
  'cms_users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('cms_users_sessions_order_idx').on(columns._order),
    index('cms_users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cms_users.id],
      name: 'cms_users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const cms_users = pgTable(
  'cms_users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    enableAPIKey: boolean('enable_a_p_i_key'),
    apiKey: varchar('api_key'),
    apiKeyIndex: varchar('api_key_index'),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index('cms_users_updated_at_idx').on(columns.updatedAt),
    index('cms_users_created_at_idx').on(columns.createdAt),
    uniqueIndex('cms_users_email_idx').on(columns.email),
  ]
)

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id').references(() => tenants.id, {
      onDelete: 'set null',
    }),
    title: varchar('title'),
    slug: varchar('slug'),
    content: jsonb('content'),
    excerpt: varchar('excerpt'),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    publishedAt: timestamp('published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_posts_status('_status').default('draft'),
  },
  (columns) => [
    index('posts_tenant_idx').on(columns.tenant),
    index('posts_featured_image_idx').on(columns.featuredImage),
    index('posts_updated_at_idx').on(columns.updatedAt),
    index('posts_created_at_idx').on(columns.createdAt),
    index('posts__status_idx').on(columns._status),
  ]
)

export const posts_rels = pgTable(
  'posts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    categoriesID: integer('categories_id'),
  },
  (columns) => [
    index('posts_rels_order_idx').on(columns.order),
    index('posts_rels_parent_idx').on(columns.parent),
    index('posts_rels_path_idx').on(columns.path),
    index('posts_rels_categories_id_idx').on(columns.categoriesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [posts.id],
      name: 'posts_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'posts_rels_categories_fk',
    }).onDelete('cascade'),
  ]
)

export const _posts_v = pgTable(
  '_posts_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => posts.id, {
      onDelete: 'set null',
    }),
    version_tenant: integer('version_tenant_id').references(() => tenants.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_content: jsonb('version_content'),
    version_excerpt: varchar('version_excerpt'),
    version_featuredImage: integer('version_featured_image_id').references(
      () => media.id,
      {
        onDelete: 'set null',
      }
    ),
    version_publishedAt: timestamp('version_published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_meta_title: varchar('version_meta_title'),
    version_meta_description: varchar('version_meta_description'),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__posts_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => [
    index('_posts_v_parent_idx').on(columns.parent),
    index('_posts_v_version_version_tenant_idx').on(columns.version_tenant),
    index('_posts_v_version_version_featured_image_idx').on(
      columns.version_featuredImage
    ),
    index('_posts_v_version_version_updated_at_idx').on(
      columns.version_updatedAt
    ),
    index('_posts_v_version_version_created_at_idx').on(
      columns.version_createdAt
    ),
    index('_posts_v_version_version__status_idx').on(columns.version__status),
    index('_posts_v_created_at_idx').on(columns.createdAt),
    index('_posts_v_updated_at_idx').on(columns.updatedAt),
    index('_posts_v_latest_idx').on(columns.latest),
    index('_posts_v_autosave_idx').on(columns.autosave),
  ]
)

export const _posts_v_rels = pgTable(
  '_posts_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    categoriesID: integer('categories_id'),
  },
  (columns) => [
    index('_posts_v_rels_order_idx').on(columns.order),
    index('_posts_v_rels_parent_idx').on(columns.parent),
    index('_posts_v_rels_path_idx').on(columns.path),
    index('_posts_v_rels_categories_id_idx').on(columns.categoriesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_posts_v.id],
      name: '_posts_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: '_posts_v_rels_categories_fk',
    }).onDelete('cascade'),
  ]
)

export const pages_blocks_content = pgTable(
  'pages_blocks_content',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    richText: jsonb('rich_text'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_content_order_idx').on(columns._order),
    index('pages_blocks_content_parent_id_idx').on(columns._parentID),
    index('pages_blocks_content_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_content_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const pages_blocks_call_to_action_links = pgTable(
  'pages_blocks_call_to_action_links',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    link_label: varchar('link_label'),
    link_url: varchar('link_url'),
    link_type:
      enum_pages_blocks_call_to_action_links_link_type('link_type').default(
        'primary'
      ),
  },
  (columns) => [
    index('pages_blocks_call_to_action_links_order_idx').on(columns._order),
    index('pages_blocks_call_to_action_links_parent_id_idx').on(
      columns._parentID
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_call_to_action.id],
      name: 'pages_blocks_call_to_action_links_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const pages_blocks_call_to_action = pgTable(
  'pages_blocks_call_to_action',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    richText: jsonb('rich_text'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_call_to_action_order_idx').on(columns._order),
    index('pages_blocks_call_to_action_parent_id_idx').on(columns._parentID),
    index('pages_blocks_call_to_action_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_call_to_action_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const pages_blocks_media_block = pgTable(
  'pages_blocks_media_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    media: integer('media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    caption: varchar('caption'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_media_block_order_idx').on(columns._order),
    index('pages_blocks_media_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_media_block_path_idx').on(columns._path),
    index('pages_blocks_media_block_media_idx').on(columns.media),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_media_block_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id').references(() => tenants.id, {
      onDelete: 'set null',
    }),
    title: varchar('title'),
    slug: varchar('slug'),
    hero_type: enum_pages_hero_type('hero_type').default('lowImpact'),
    hero_richText: jsonb('hero_rich_text'),
    hero_media: integer('hero_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    htmlContent: varchar('html_content'),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    meta_image: integer('meta_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status('_status').default('draft'),
  },
  (columns) => [
    index('pages_tenant_idx').on(columns.tenant),
    index('pages_hero_hero_media_idx').on(columns.hero_media),
    index('pages_meta_meta_image_idx').on(columns.meta_image),
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
    index('pages__status_idx').on(columns._status),
  ]
)

export const _pages_v_blocks_content = pgTable(
  '_pages_v_blocks_content',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    richText: jsonb('rich_text'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_content_order_idx').on(columns._order),
    index('_pages_v_blocks_content_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_content_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_content_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const _pages_v_blocks_call_to_action_links = pgTable(
  '_pages_v_blocks_call_to_action_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    link_label: varchar('link_label'),
    link_url: varchar('link_url'),
    link_type:
      enum__pages_v_blocks_call_to_action_links_link_type('link_type').default(
        'primary'
      ),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_pages_v_blocks_call_to_action_links_order_idx').on(columns._order),
    index('_pages_v_blocks_call_to_action_links_parent_id_idx').on(
      columns._parentID
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v_blocks_call_to_action.id],
      name: '_pages_v_blocks_call_to_action_links_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const _pages_v_blocks_call_to_action = pgTable(
  '_pages_v_blocks_call_to_action',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    richText: jsonb('rich_text'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_call_to_action_order_idx').on(columns._order),
    index('_pages_v_blocks_call_to_action_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_call_to_action_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_call_to_action_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const _pages_v_blocks_media_block = pgTable(
  '_pages_v_blocks_media_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: serial('id').primaryKey(),
    media: integer('media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    caption: varchar('caption'),
    _uuid: varchar('_uuid'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('_pages_v_blocks_media_block_order_idx').on(columns._order),
    index('_pages_v_blocks_media_block_parent_id_idx').on(columns._parentID),
    index('_pages_v_blocks_media_block_path_idx').on(columns._path),
    index('_pages_v_blocks_media_block_media_idx').on(columns.media),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_pages_v.id],
      name: '_pages_v_blocks_media_block_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const _pages_v = pgTable(
  '_pages_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => pages.id, {
      onDelete: 'set null',
    }),
    version_tenant: integer('version_tenant_id').references(() => tenants.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_hero_type:
      enum__pages_v_version_hero_type('version_hero_type').default('lowImpact'),
    version_hero_richText: jsonb('version_hero_rich_text'),
    version_hero_media: integer('version_hero_media_id').references(
      () => media.id,
      {
        onDelete: 'set null',
      }
    ),
    version_htmlContent: varchar('version_html_content'),
    version_meta_title: varchar('version_meta_title'),
    version_meta_description: varchar('version_meta_description'),
    version_meta_image: integer('version_meta_image_id').references(
      () => media.id,
      {
        onDelete: 'set null',
      }
    ),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__pages_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => [
    index('_pages_v_parent_idx').on(columns.parent),
    index('_pages_v_version_version_tenant_idx').on(columns.version_tenant),
    index('_pages_v_version_hero_version_hero_media_idx').on(
      columns.version_hero_media
    ),
    index('_pages_v_version_meta_version_meta_image_idx').on(
      columns.version_meta_image
    ),
    index('_pages_v_version_version_updated_at_idx').on(
      columns.version_updatedAt
    ),
    index('_pages_v_version_version_created_at_idx').on(
      columns.version_createdAt
    ),
    index('_pages_v_version_version__status_idx').on(columns.version__status),
    index('_pages_v_created_at_idx').on(columns.createdAt),
    index('_pages_v_updated_at_idx').on(columns.updatedAt),
    index('_pages_v_latest_idx').on(columns.latest),
    index('_pages_v_autosave_idx').on(columns.autosave),
  ]
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id').references(() => tenants.id, {
      onDelete: 'set null',
    }),
    title: varchar('title').notNull(),
    slug: varchar('slug'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('categories_tenant_idx').on(columns.tenant),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ]
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    tenant: integer('tenant_id').references(() => tenants.id, {
      onDelete: 'set null',
    }),
    alt: varchar('alt').notNull(),
    caption: jsonb('caption'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_tenant_idx').on(columns.tenant),
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ]
)

export const payload_mcp_api_keys = pgTable(
  'payload_mcp_api_keys',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => cms_users.id, {
        onDelete: 'set null',
      }),
    label: varchar('label'),
    description: varchar('description'),
    posts_find: boolean('posts_find').default(false),
    posts_create: boolean('posts_create').default(false),
    posts_update: boolean('posts_update').default(false),
    posts_delete: boolean('posts_delete').default(false),
    pages_find: boolean('pages_find').default(false),
    pages_create: boolean('pages_create').default(false),
    pages_update: boolean('pages_update').default(false),
    pages_delete: boolean('pages_delete').default(false),
    categories_find: boolean('categories_find').default(false),
    categories_create: boolean('categories_create').default(false),
    categories_update: boolean('categories_update').default(false),
    categories_delete: boolean('categories_delete').default(false),
    header_find: boolean('header_find').default(false),
    header_update: boolean('header_update').default(false),
    footer_find: boolean('footer_find').default(false),
    footer_update: boolean('footer_update').default(false),
    settings_find: boolean('settings_find').default(false),
    settings_update: boolean('settings_update').default(false),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    enableAPIKey: boolean('enable_a_p_i_key'),
    apiKey: varchar('api_key'),
    apiKeyIndex: varchar('api_key_index'),
  },
  (columns) => [
    index('payload_mcp_api_keys_user_idx').on(columns.user),
    index('payload_mcp_api_keys_updated_at_idx').on(columns.updatedAt),
    index('payload_mcp_api_keys_created_at_idx').on(columns.createdAt),
  ]
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)]
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ]
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    tenantsID: integer('tenants_id'),
    'cms-usersID': integer('cms_users_id'),
    postsID: integer('posts_id'),
    pagesID: integer('pages_id'),
    categoriesID: integer('categories_id'),
    mediaID: integer('media_id'),
    'payload-mcp-api-keysID': integer('payload_mcp_api_keys_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_tenants_id_idx').on(columns.tenantsID),
    index('payload_locked_documents_rels_cms_users_id_idx').on(
      columns['cms-usersID']
    ),
    index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_categories_id_idx').on(
      columns.categoriesID
    ),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_payload_mcp_api_keys_id_idx').on(
      columns['payload-mcp-api-keysID']
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tenantsID']],
      foreignColumns: [tenants.id],
      name: 'payload_locked_documents_rels_tenants_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['cms-usersID']],
      foreignColumns: [cms_users.id],
      name: 'payload_locked_documents_rels_cms_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['payload-mcp-api-keysID']],
      foreignColumns: [payload_mcp_api_keys.id],
      name: 'payload_locked_documents_rels_payload_mcp_api_keys_fk',
    }).onDelete('cascade'),
  ]
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ]
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'cms-usersID': integer('cms_users_id'),
    'payload-mcp-api-keysID': integer('payload_mcp_api_keys_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_cms_users_id_idx').on(
      columns['cms-usersID']
    ),
    index('payload_preferences_rels_payload_mcp_api_keys_id_idx').on(
      columns['payload-mcp-api-keysID']
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['cms-usersID']],
      foreignColumns: [cms_users.id],
      name: 'payload_preferences_rels_cms_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['payload-mcp-api-keysID']],
      foreignColumns: [payload_mcp_api_keys.id],
      name: 'payload_preferences_rels_payload_mcp_api_keys_fk',
    }).onDelete('cascade'),
  ]
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ]
)

export const header_nav_items = pgTable(
  'header_nav_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    link_label: varchar('link_label').notNull(),
    link_url: varchar('link_url').notNull(),
  },
  (columns) => [
    index('header_nav_items_order_idx').on(columns._order),
    index('header_nav_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [header.id],
      name: 'header_nav_items_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const header = pgTable('header', {
  id: serial('id').primaryKey(),
  cta_label: varchar('cta_label'),
  cta_url: varchar('cta_url'),
  updatedAt: timestamp('updated_at', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp('created_at', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }),
})

export const footer_columns_links = pgTable(
  'footer_columns_links',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    url: varchar('url').notNull(),
  },
  (columns) => [
    index('footer_columns_links_order_idx').on(columns._order),
    index('footer_columns_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [footer_columns.id],
      name: 'footer_columns_links_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const footer_columns = pgTable(
  'footer_columns',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    heading: varchar('heading'),
  },
  (columns) => [
    index('footer_columns_order_idx').on(columns._order),
    index('footer_columns_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [footer.id],
      name: 'footer_columns_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const footer_socials = pgTable(
  'footer_socials',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    platform: enum_footer_socials_platform('platform'),
    url: varchar('url').notNull(),
  },
  (columns) => [
    index('footer_socials_order_idx').on(columns._order),
    index('footer_socials_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [footer.id],
      name: 'footer_socials_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const footer = pgTable('footer', {
  id: serial('id').primaryKey(),
  copyright: varchar('copyright'),
  updatedAt: timestamp('updated_at', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp('created_at', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }),
})

export const settings = pgTable(
  'settings',
  {
    id: serial('id').primaryKey(),
    siteName: varchar('site_name').notNull(),
    siteDescription: varchar('site_description'),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    favicon: integer('favicon_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    typography_bodyFont: varchar('typography_body_font').default('Inter'),
    typography_headingFont: varchar('typography_heading_font').default('Inter'),
    typography_baseFontSize: enum_settings_typography_base_font_size(
      'typography_base_font_size'
    ).default('16'),
    colors_primary: varchar('colors_primary').default('#111111'),
    colors_background: varchar('colors_background').default('#ffffff'),
    colors_text: varchar('colors_text').default('#111111'),
    analytics_googleAnalyticsId: varchar('analytics_google_analytics_id'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index('settings_logo_idx').on(columns.logo),
    index('settings_favicon_idx').on(columns.favicon),
  ]
)

export const relations_tenants = relations(tenants, () => ({}))
export const relations_cms_users_roles = relations(
  cms_users_roles,
  ({ one }) => ({
    parent: one(cms_users, {
      fields: [cms_users_roles.parent],
      references: [cms_users.id],
      relationName: 'roles',
    }),
  })
)
export const relations_cms_users_tenants = relations(
  cms_users_tenants,
  ({ one }) => ({
    _parentID: one(cms_users, {
      fields: [cms_users_tenants._parentID],
      references: [cms_users.id],
      relationName: 'tenants',
    }),
    tenant: one(tenants, {
      fields: [cms_users_tenants.tenant],
      references: [tenants.id],
      relationName: 'tenant',
    }),
  })
)
export const relations_cms_users_sessions = relations(
  cms_users_sessions,
  ({ one }) => ({
    _parentID: one(cms_users, {
      fields: [cms_users_sessions._parentID],
      references: [cms_users.id],
      relationName: 'sessions',
    }),
  })
)
export const relations_cms_users = relations(cms_users, ({ many }) => ({
  roles: many(cms_users_roles, {
    relationName: 'roles',
  }),
  tenants: many(cms_users_tenants, {
    relationName: 'tenants',
  }),
  sessions: many(cms_users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_posts_rels = relations(posts_rels, ({ one }) => ({
  parent: one(posts, {
    fields: [posts_rels.parent],
    references: [posts.id],
    relationName: '_rels',
  }),
  categoriesID: one(categories, {
    fields: [posts_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
}))
export const relations_posts = relations(posts, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [posts.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  featuredImage: one(media, {
    fields: [posts.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
  _rels: many(posts_rels, {
    relationName: '_rels',
  }),
}))
export const relations__posts_v_rels = relations(_posts_v_rels, ({ one }) => ({
  parent: one(_posts_v, {
    fields: [_posts_v_rels.parent],
    references: [_posts_v.id],
    relationName: '_rels',
  }),
  categoriesID: one(categories, {
    fields: [_posts_v_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
}))
export const relations__posts_v = relations(_posts_v, ({ one, many }) => ({
  parent: one(posts, {
    fields: [_posts_v.parent],
    references: [posts.id],
    relationName: 'parent',
  }),
  version_tenant: one(tenants, {
    fields: [_posts_v.version_tenant],
    references: [tenants.id],
    relationName: 'version_tenant',
  }),
  version_featuredImage: one(media, {
    fields: [_posts_v.version_featuredImage],
    references: [media.id],
    relationName: 'version_featuredImage',
  }),
  _rels: many(_posts_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_pages_blocks_content = relations(
  pages_blocks_content,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_content._parentID],
      references: [pages.id],
      relationName: '_blocks_content',
    }),
  })
)
export const relations_pages_blocks_call_to_action_links = relations(
  pages_blocks_call_to_action_links,
  ({ one }) => ({
    _parentID: one(pages_blocks_call_to_action, {
      fields: [pages_blocks_call_to_action_links._parentID],
      references: [pages_blocks_call_to_action.id],
      relationName: 'links',
    }),
  })
)
export const relations_pages_blocks_call_to_action = relations(
  pages_blocks_call_to_action,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_call_to_action._parentID],
      references: [pages.id],
      relationName: '_blocks_callToAction',
    }),
    links: many(pages_blocks_call_to_action_links, {
      relationName: 'links',
    }),
  })
)
export const relations_pages_blocks_media_block = relations(
  pages_blocks_media_block,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_media_block._parentID],
      references: [pages.id],
      relationName: '_blocks_mediaBlock',
    }),
    media: one(media, {
      fields: [pages_blocks_media_block.media],
      references: [media.id],
      relationName: 'media',
    }),
  })
)
export const relations_pages = relations(pages, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [pages.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  hero_media: one(media, {
    fields: [pages.hero_media],
    references: [media.id],
    relationName: 'hero_media',
  }),
  _blocks_content: many(pages_blocks_content, {
    relationName: '_blocks_content',
  }),
  _blocks_callToAction: many(pages_blocks_call_to_action, {
    relationName: '_blocks_callToAction',
  }),
  _blocks_mediaBlock: many(pages_blocks_media_block, {
    relationName: '_blocks_mediaBlock',
  }),
  meta_image: one(media, {
    fields: [pages.meta_image],
    references: [media.id],
    relationName: 'meta_image',
  }),
}))
export const relations__pages_v_blocks_content = relations(
  _pages_v_blocks_content,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_content._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_content',
    }),
  })
)
export const relations__pages_v_blocks_call_to_action_links = relations(
  _pages_v_blocks_call_to_action_links,
  ({ one }) => ({
    _parentID: one(_pages_v_blocks_call_to_action, {
      fields: [_pages_v_blocks_call_to_action_links._parentID],
      references: [_pages_v_blocks_call_to_action.id],
      relationName: 'links',
    }),
  })
)
export const relations__pages_v_blocks_call_to_action = relations(
  _pages_v_blocks_call_to_action,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_call_to_action._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_callToAction',
    }),
    links: many(_pages_v_blocks_call_to_action_links, {
      relationName: 'links',
    }),
  })
)
export const relations__pages_v_blocks_media_block = relations(
  _pages_v_blocks_media_block,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_media_block._parentID],
      references: [_pages_v.id],
      relationName: '_blocks_mediaBlock',
    }),
    media: one(media, {
      fields: [_pages_v_blocks_media_block.media],
      references: [media.id],
      relationName: 'media',
    }),
  })
)
export const relations__pages_v = relations(_pages_v, ({ one, many }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: 'parent',
  }),
  version_tenant: one(tenants, {
    fields: [_pages_v.version_tenant],
    references: [tenants.id],
    relationName: 'version_tenant',
  }),
  version_hero_media: one(media, {
    fields: [_pages_v.version_hero_media],
    references: [media.id],
    relationName: 'version_hero_media',
  }),
  _blocks_content: many(_pages_v_blocks_content, {
    relationName: '_blocks_content',
  }),
  _blocks_callToAction: many(_pages_v_blocks_call_to_action, {
    relationName: '_blocks_callToAction',
  }),
  _blocks_mediaBlock: many(_pages_v_blocks_media_block, {
    relationName: '_blocks_mediaBlock',
  }),
  version_meta_image: one(media, {
    fields: [_pages_v.version_meta_image],
    references: [media.id],
    relationName: 'version_meta_image',
  }),
}))
export const relations_categories = relations(categories, ({ one }) => ({
  tenant: one(tenants, {
    fields: [categories.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
}))
export const relations_media = relations(media, ({ one }) => ({
  tenant: one(tenants, {
    fields: [media.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
}))
export const relations_payload_mcp_api_keys = relations(
  payload_mcp_api_keys,
  ({ one }) => ({
    user: one(cms_users, {
      fields: [payload_mcp_api_keys.user],
      references: [cms_users.id],
      relationName: 'user',
    }),
  })
)
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    tenantsID: one(tenants, {
      fields: [payload_locked_documents_rels.tenantsID],
      references: [tenants.id],
      relationName: 'tenants',
    }),
    'cms-usersID': one(cms_users, {
      fields: [payload_locked_documents_rels['cms-usersID']],
      references: [cms_users.id],
      relationName: 'cms-users',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    'payload-mcp-api-keysID': one(payload_mcp_api_keys, {
      fields: [payload_locked_documents_rels['payload-mcp-api-keysID']],
      references: [payload_mcp_api_keys.id],
      relationName: 'payload-mcp-api-keys',
    }),
  })
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  })
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    'cms-usersID': one(cms_users, {
      fields: [payload_preferences_rels['cms-usersID']],
      references: [cms_users.id],
      relationName: 'cms-users',
    }),
    'payload-mcp-api-keysID': one(payload_mcp_api_keys, {
      fields: [payload_preferences_rels['payload-mcp-api-keysID']],
      references: [payload_mcp_api_keys.id],
      relationName: 'payload-mcp-api-keys',
    }),
  })
)
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: '_rels',
    }),
  })
)
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({})
)
export const relations_header_nav_items = relations(
  header_nav_items,
  ({ one }) => ({
    _parentID: one(header, {
      fields: [header_nav_items._parentID],
      references: [header.id],
      relationName: 'navItems',
    }),
  })
)
export const relations_header = relations(header, ({ many }) => ({
  navItems: many(header_nav_items, {
    relationName: 'navItems',
  }),
}))
export const relations_footer_columns_links = relations(
  footer_columns_links,
  ({ one }) => ({
    _parentID: one(footer_columns, {
      fields: [footer_columns_links._parentID],
      references: [footer_columns.id],
      relationName: 'links',
    }),
  })
)
export const relations_footer_columns = relations(
  footer_columns,
  ({ one, many }) => ({
    _parentID: one(footer, {
      fields: [footer_columns._parentID],
      references: [footer.id],
      relationName: 'columns',
    }),
    links: many(footer_columns_links, {
      relationName: 'links',
    }),
  })
)
export const relations_footer_socials = relations(
  footer_socials,
  ({ one }) => ({
    _parentID: one(footer, {
      fields: [footer_socials._parentID],
      references: [footer.id],
      relationName: 'socials',
    }),
  })
)
export const relations_footer = relations(footer, ({ many }) => ({
  columns: many(footer_columns, {
    relationName: 'columns',
  }),
  socials: many(footer_socials, {
    relationName: 'socials',
  }),
}))
export const relations_settings = relations(settings, ({ one }) => ({
  logo: one(media, {
    fields: [settings.logo],
    references: [media.id],
    relationName: 'logo',
  }),
  favicon: one(media, {
    fields: [settings.favicon],
    references: [media.id],
    relationName: 'favicon',
  }),
}))

type DatabaseSchema = {
  enum_tenants_template: typeof enum_tenants_template
  enum_tenants_status: typeof enum_tenants_status
  enum_cms_users_roles: typeof enum_cms_users_roles
  enum_posts_status: typeof enum_posts_status
  enum__posts_v_version_status: typeof enum__posts_v_version_status
  enum_pages_blocks_call_to_action_links_link_type: typeof enum_pages_blocks_call_to_action_links_link_type
  enum_pages_hero_type: typeof enum_pages_hero_type
  enum_pages_status: typeof enum_pages_status
  enum__pages_v_blocks_call_to_action_links_link_type: typeof enum__pages_v_blocks_call_to_action_links_link_type
  enum__pages_v_version_hero_type: typeof enum__pages_v_version_hero_type
  enum__pages_v_version_status: typeof enum__pages_v_version_status
  enum_footer_socials_platform: typeof enum_footer_socials_platform
  enum_settings_typography_base_font_size: typeof enum_settings_typography_base_font_size
  tenants: typeof tenants
  cms_users_roles: typeof cms_users_roles
  cms_users_tenants: typeof cms_users_tenants
  cms_users_sessions: typeof cms_users_sessions
  cms_users: typeof cms_users
  posts: typeof posts
  posts_rels: typeof posts_rels
  _posts_v: typeof _posts_v
  _posts_v_rels: typeof _posts_v_rels
  pages_blocks_content: typeof pages_blocks_content
  pages_blocks_call_to_action_links: typeof pages_blocks_call_to_action_links
  pages_blocks_call_to_action: typeof pages_blocks_call_to_action
  pages_blocks_media_block: typeof pages_blocks_media_block
  pages: typeof pages
  _pages_v_blocks_content: typeof _pages_v_blocks_content
  _pages_v_blocks_call_to_action_links: typeof _pages_v_blocks_call_to_action_links
  _pages_v_blocks_call_to_action: typeof _pages_v_blocks_call_to_action
  _pages_v_blocks_media_block: typeof _pages_v_blocks_media_block
  _pages_v: typeof _pages_v
  categories: typeof categories
  media: typeof media
  payload_mcp_api_keys: typeof payload_mcp_api_keys
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  header_nav_items: typeof header_nav_items
  header: typeof header
  footer_columns_links: typeof footer_columns_links
  footer_columns: typeof footer_columns
  footer_socials: typeof footer_socials
  footer: typeof footer
  settings: typeof settings
  relations_tenants: typeof relations_tenants
  relations_cms_users_roles: typeof relations_cms_users_roles
  relations_cms_users_tenants: typeof relations_cms_users_tenants
  relations_cms_users_sessions: typeof relations_cms_users_sessions
  relations_cms_users: typeof relations_cms_users
  relations_posts_rels: typeof relations_posts_rels
  relations_posts: typeof relations_posts
  relations__posts_v_rels: typeof relations__posts_v_rels
  relations__posts_v: typeof relations__posts_v
  relations_pages_blocks_content: typeof relations_pages_blocks_content
  relations_pages_blocks_call_to_action_links: typeof relations_pages_blocks_call_to_action_links
  relations_pages_blocks_call_to_action: typeof relations_pages_blocks_call_to_action
  relations_pages_blocks_media_block: typeof relations_pages_blocks_media_block
  relations_pages: typeof relations_pages
  relations__pages_v_blocks_content: typeof relations__pages_v_blocks_content
  relations__pages_v_blocks_call_to_action_links: typeof relations__pages_v_blocks_call_to_action_links
  relations__pages_v_blocks_call_to_action: typeof relations__pages_v_blocks_call_to_action
  relations__pages_v_blocks_media_block: typeof relations__pages_v_blocks_media_block
  relations__pages_v: typeof relations__pages_v
  relations_categories: typeof relations_categories
  relations_media: typeof relations_media
  relations_payload_mcp_api_keys: typeof relations_payload_mcp_api_keys
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_header_nav_items: typeof relations_header_nav_items
  relations_header: typeof relations_header
  relations_footer_columns_links: typeof relations_footer_columns_links
  relations_footer_columns: typeof relations_footer_columns
  relations_footer_socials: typeof relations_footer_socials
  relations_footer: typeof relations_footer
  relations_settings: typeof relations_settings
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
