export const militaryCards = [
  {
    number: "01",
    slug: "whole-field",
    category: "System",
    title: "The Whole Field",
    subtitle: "Purpose · Force · Sustainment · Consequence · Return",
    kernel: "Purpose organizes force; consequence returns through bodies, families, landscapes, institutions, and memory.",
    toward: "Whole-field orientation makes hidden dependencies and deferred consequences visible.",
    away: "Totalizing abstraction can make particular people, responsibilities, sources, and disagreements disappear inside the word system.",
    sense: "Name the boundary, purpose, participants, resources, forces, clocks, perspectives, and unknowns.",
    choose: "Compare capability, legitimacy, sustainment, human consequence, reversibility, and information gained.",
    act: "Require authority, interfaces, receipts, stopping conditions, and remedy.",
    learn: "Compare expected and observed outcomes, including effects shifted onto civilians, Veterans, families, and environments.",
    question: "Which part of the field has declared itself the whole?",
  },
  {
    number: "02",
    slug: "hidden-chain",
    category: "Power",
    title: "The Hidden Chain",
    subtitle: "Capability exists only when the chain holds",
    kernel: "Intention becomes real only when matter, people, time, maintenance, and care arrive in usable condition—and the return flow is carried too.",
    toward: "Provision, endurance, recovery, readiness, redundancy, and an honest account of what a strategy values.",
    away: "Bottleneck, extraction, waste, brittle optimization, invisible labor, unequal burden, and false availability.",
    sense: "Measure demand, capacity, condition, route, lead time, ownership, maintenance, return flow, and uncertainty.",
    choose: "Compare throughput, resilience, cost, exposure, substitution, delay, and the option to reduce demand.",
    act: "Bind movement to accountable orders, custody, delivery proof, inspection, recovery, and remedy.",
    learn: "Compare planned and actual consumption, delay, damage, maintenance, labor, waste, and human cost.",
    question: "Who carries the visible action’s invisible weight?",
  },
  {
    number: "03",
    slug: "73-easting",
    category: "Battle",
    title: "73 Easting",
    subtitle: "A grid line, a battle, a long aftermath",
    kernel: "A map grid line became a threshold where reconnaissance, command, training, weather, sensors, weapons, logistics, and Iraqi resistance converged on 26 February 1991.",
    toward: "Study interaction among mission, mutual support, initiative, reporting, training, weather, sustainment, Iraqi action, and adjacent formations.",
    away: "A decisive-battle story can let one technology, leader, troop, or national account stand in for the action and its aftermath.",
    sense: "Reconstruct mission, map, weather, visibility, locations, reports, uncertainty, opposing action, and source perspective.",
    choose: "Compare decisions available at each echelon without giving historical actors hindsight.",
    act: "Use only for history, education, and public analysis—not contemporary targeting or tactical instruction.",
    learn: "Separate lessons claimed at the time from doctrine, simulation, memory, official history, and unresolved perspectives.",
    question: "What disappears when the action ends at tactical victory?",
  },
  {
    number: "04",
    slug: "service-continues",
    category: "Veterans",
    title: "Service Continues",
    subtitle: "The institution stops carrying; life does not",
    kernel: "Military service continues after separation through bodies, identity, families, work, disability, care, benefits, community, grief, humor, and memory.",
    toward: "Recognition, participant agency, useful continuity, peer and family connection, renewed purpose, and authority over what is shared.",
    away: "Abandonment, identity capture, compulsory heroism, compulsory damage, isolation, or one memory made to speak for everyone.",
    sense: "Ask what continues, what changed, what remains private, and which institution has actual authority.",
    choose: "Include passing, joking, staying literal, asking for current information, contacting a peer, or seeking qualified help.",
    act: "Use explicit participant-authorized handoffs; keep private health, benefits, and family details out of the shared graph.",
    learn: "Let correction and dissent remain attributable; a story may deepen the System without becoming universal truth.",
    question: "What did the institution end on paper that continued in life?",
  },
  {
    number: "05",
    slug: "gulf-war-illness",
    category: "Care",
    title: "Gulf War Illness",
    subtitle: "The symptoms are real; the pattern is systemic",
    kernel: "A varied cluster of chronic symptoms can remain consequential even when one cause, test, or universal case definition does not contain every Veteran’s experience.",
    toward: "Recognition, individualized evaluation, current navigation, symptom-specific care, participant credibility, and qualified research.",
    away: "Dismissal because causation is uncertain; diagnosis by card; one-cause certainty; stereotypes; or stale eligibility rules.",
    sense: "Separate symptoms, diagnoses, exposure concerns, research definitions, benefits rules, participant statements, and unknowns.",
    choose: "Consider qualified care, an environmental-health coordinator, the Gulf War Registry, or current benefits help as appropriate.",
    act: "Route to qualified care or official and accredited help; the card cannot diagnose, treat, or determine service connection.",
    learn: "Preserve what helped and what remained unresolved without turning one experience into the cohort.",
    question: "Which uncertainty is being mistaken for permission to dismiss the person?",
  },
  {
    number: "06",
    slug: "va-navigation",
    category: "Care",
    title: "Different Doors",
    subtitle: "The door is not the decision",
    kernel: "A registry exam, health-care enrollment, clinical referral, disability claim, accredited representation, Vet Center service, and crisis response are different doors.",
    toward: "Current official information, the correct program, a human contact, clear records, consent, a receipt, and a visible remedy path.",
    away: "Stale rules, duplicated forms, dropped handoffs, informal authority, missing records, or symbolic reflection mistaken for eligibility.",
    sense: "Identify the actual question: health, registry, referral, enrollment, claim, appeal, accredited help, counseling, family support, or crisis.",
    choose: "Compare current pathways and what each requires; the fitting move may be a warm handoff rather than another document.",
    act: "Make only participant-authorized connections; do not submit, disclose, or decide on someone’s behalf.",
    learn: "Record whether the handoff connected and what remedy exists—without copying private details into the graph.",
    question: "Which door has authority to answer this question?",
  },
  {
    number: "07",
    slug: "connection-creates-time",
    category: "Crisis",
    title: "Connection Creates Time",
    subtitle: "Stay · Connect · Create distance · Hand off",
    kernel: "During a suicidal crisis, immediate connection, safety planning, and greater time or distance from lethal means can open space for care; the card is a doorway, never the responder.",
    toward: "Immediate human connection, hope, time, safety planning, support networks, a qualified responder, and greater distance from lethal means.",
    away: "Isolation, delay, shame, compelled disclosure, method detail, unattended risk, or an automated system substituting for support.",
    sense: "Recognize that urgent support may be needed without assigning a personal score or demanding a story.",
    choose: "Offer current qualified channels appropriate to the moment.",
    act: "Make the human handoff now and follow the qualified responder’s safety guidance.",
    learn: "Later, review whether the pathway was accessible and continuous without storing private crisis details.",
    question: "What safe human connection can create the next hour?",
  },
  {
    number: "08",
    slug: "family-sustainment",
    category: "Families",
    title: "Sustainment Is Shared Work",
    subtitle: "Family and chosen networks carry the long field",
    kernel: "Families and chosen networks often carry scheduling, care, records, transportation, income shocks, grief, advocacy, and ordinary continuity after formal systems recede.",
    toward: "Visible and shared care labor, consent, boundaries, respite, resources, mutual support, and institutional responsibility.",
    away: "One person becomes the permanent driver, scheduler, recorder, advocate, translator, income buffer, historian, and crisis system.",
    sense: "Ask who carries which work, with what resources, authority, consent, time, and strain.",
    choose: "Include boundaries, respite, redistribution, official navigation, peer support, professional care, or saying no.",
    act: "Make participant-authorized handoffs and protect private information.",
    learn: "Notice which support helped, which burden moved rather than disappeared, and what the institution must repair.",
    question: "Which system is functioning only because a household absorbs its failures?",
  },
] as const;

export type MilitaryCard = (typeof militaryCards)[number];
